runtime! debian.vim

if has("syntax")
  syntax on
endif

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("autocmd")
  filetype plugin indent on
endif

autocmd BufWritePre * %s/\s\+$//e

set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set hlsearch
set nowrap

